### PRODUCTS INDEX
GET http://localhost:3000/products.json?category=bikes
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzU0NTY1ODB9.7xNB8DfBJ4v9yX8eXUNLV1e_Sn_xJ8nFmGo_qpAht2c

### PRODUCT SHOW
GET http://localhost:3000/products/2.json 

### PRODUCT CREATE

POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Dainese Blackjack Gloves",
  "price": 125,
  "image_url": "https://www.revzilla.com/product_images/0217/2147/dainese_blackjack_gloves_300x300.jpg",
  "description": "Timeless Italian taste, quality leather construction and nothing more. The Dainese Blackjack Gloves give off good vibes for the stylish summer rider."
}

### PRODUCT UPDATE

PATCH http://localhost:3000/products/4.json
Content-Type: application/json

{
  "price": "bill"
}

### PRODUCT DESTROY

DELETE http://localhost:3000/products/5.json

#########################################################
### SUPPLIER INDEX
GET http://localhost:3000/suppliers.json

### SUPPLIER SHOW
GET http://localhost:3000/suppliers/2.json

### SUPPLIER CREATE
POST http://localhost:3000/suppliers.json
Content-Type: application/json

{
  "name": 
  "email":
  "phone_number":
}

### SUPPLIER UPDATE
PATCH http://localhost:3000/suppliers/4.json
Content-Type: application/json

{
  "email":
}

### SUPPLIER DESTROY
DELETE http://localhost:3000/suppliers/5.json

#######################################################
### IMAGE INDEX
GET http://localhost:3000/images.json

### IMAGE SHOW
GET http://localhost:3000/images/2.json

### IMAGE CREATE
POST http://localhost:3000/images.json
Content-Type: application/json

{
  "url":
  "product_id"
}

### IMAGE UPDATE
PATCH http://localhost:3000/images/4.json
Content-Type: application/json

{
  "url":
}

### IMAGE DESTROY
DELETE http://localhost:3000/images/.json


#################################################
### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Phil jobe",
  "email": "phil@example.com"       ,
  "password": "password",
  "password_confirmation": "password"
}

################################################
### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

#################################################
### Photos create
POST http://localhost:3000/photos
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjozLCJleHAiOjE2Mjk5OTI4NjR9.G2ExsrDYn3oE0vJkvm4T6Po2GbNpH5cqTEaVPVuK_MA
Content-Type: application/json

{
  "name": "Test name",
  "width": 640,
  "height": 480
}

### Orders index
GET http://localhost:3000/orders.json 

### Orders show
GET http://localhost:3000/orders/1.json 


### Orders create 
POST http://localhost:3000/orders

Content-Type: application/json

{
  
  "product_id": 2,
  "quantity": 2
  
}

### CARTED PRODUCTS CREATE
POST http://localhost:3000/carted_products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzU1MzA3NjB9.OgGqLM8-3TPAhEnbv9_SH2AdD1Ln0yKLec8fP1NgLDE 
Content-Type: application/json

  {
    "product_id": 1,
    "quantity": 1
  }

### CARTED PRODUCTS DESTROY
DELETE http://localhost:3000/carted_products/4.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzU1MzA3NjB9.OgGqLM8-3TPAhEnbv9_SH2AdD1Ln0yKLec8fP1NgLDE 
Content-Type: application/json